services:
  frontend:
    image: nginx:latest
    container_name: fronted-container
    ports:
      - 5173:80
    environment:
      - DEPLOYMENT=development
    volumes:
      - ./frontend/react/dist:/usr/share/nginx/html
      - ./.dockerdata/nginx/nginx.conf:/etc/nginx/nginx.conf

  postgres:
    container_name: bungalow_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      PGDATA: /data/postgres
    volumes:
      - .dockerdata/postgres:/data/postgres
      - ./database/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - bungalow
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@k.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - .dockerdata/pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - bungalow
    restart: unless-stopped

  backend:
    container_name: bungalow_backend_container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - bungalow
    environment:
      - CLIENT_ID=bungalo-backend
      - CLIENT_SECRET=aqzNczcvGJieSBvRhdNKCWbvgLgQzoBW
      - INTROSPECT_ENDPOINT=https://keycloak.julylab.org/realms/master/protocol/openid-connect/token/introspect
      - DB_HOST=bungalow_postgres_container
      - DB_USER=bungalow_user
      - DB_PASSWORD=1234
      - DB_NAME=bungalow
      - DB_PORT=5432
networks:
  bungalow:
    driver: bridge
