CREATE USER personal WITH PASSWORD '1234';

CREATE DATABASE bungalow;

GRANT ALL PRIVILEGES ON DATABASE bungalow TO personal;

CREATE TABLE IF NOT EXISTS People (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) NOT NULL
);